### ISSUE TITLE
rename "quick review" button

### ISSUE THREAD

**Issue by cebarahona** [stats4sd/Sampling-Decision-Assistant#20]
I think if this button leads the user to a screen where all the questions can be seen and answered sequentially, we should call this button "Question-based mode"

The next page should say: Here you will be able to answer all the questions in the assistant in one single screen. This means that you will have minimal help options and access to other types of support, but it will allow experienced users to go through the key questions much faster"

To be consistent we should rename the first button "Step by Step mode". and it should start with a paragraph that says

"Here you will use the Sampling Decision Assistant following key decision stages in your sampling design. You will have easy access to extra help and examples about how to make the decisions that will form you sampling design"

**Comment by chrismclarke** [comment]
implemented (v0.2.0), closing
