### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by cebarahona** [stats4sd/Sampling-Decision-Assistant#21]
Change output from PDF to an editable format

As discussed, Chris, we need the output to be produced as an editable format. The guiding question and the answer provided should go together. The idea is that this becomes the core to a sampling methodology section in a protocol or report.

**Comment by chrismclarke** [comment]
That's good to hear as PDFs are simply a pain to generate and format nicely from html. I'll first work on csv format.

**Comment by chrismclarke** [comment]
Output to xlsx implemented (v0.2.1). review by clicking 'export' from the  question-based mode page (https://unhcr-sampling-assistant.firebaseapp.com/#/questions).

Still needs testing on mobile, but do you think we need to provide any further functionality? (e.g. more file types, an output preview page etc?)
