### ISSUE TITLE
Introduction for "indicators" section

### ISSUE THREAD

**Issue by cebarahona** [stats4sd/Sampling-Decision-Assistant#23]
Here we need to say:

In this section you need to select one indicator that will guide some of your decisions about sampling. 

A good deal of the statistics theory that is used in sampling is based on estimating the value of an indicator for a population. This produces some tension because in practice we want to estimate multiple indicators. The way this tension is resolved it to choose one key indicator that can be used to make important decisions.

There are two things you will need to know about the indicator: 

1. How variable it is
2. What is the margin of error that you are prepared to accept in the estimation process

The following questions will help you in thinking about these issues

You can access extra help in the section "Audio" and "Video" where some more technical issues are discussed to help you developing a better understanding that should help in your decision making.

**Comment by chrismclarke** [comment]
implemented, review at https://unhcr-sampling-assistant.firebaseapp.com/#/indicators
(version 0.2.0)
