### ISSUE TITLE
Possible audio/video/text for indicators

### ISSUE THREAD

**Issue by cebarahona** [stats4sd/Sampling-Decision-Assistant#24]
These are possible extras for this stage:

What is an indicator
A list of indicators commonly used in UNHCR work
How to work out the level of variability of an indicator
What is "margin of error"

Chris, how do you think these resources should be displayed. It is likely that more than one item will be available under any of the categories: audio/video/etc

**Comment by chrismclarke** [comment]
My opinion would be to put all extras/resources in a single section entitled resources (as suggested in  #25). Resources could simply appear as a list with an icon to indicate what type of resource it is and a brief description.
