### ISSUE TITLE
Pros/Cons

### ISSUE THREAD

**Issue by cebarahona** [stats4sd/Sampling-Decision-Assistant#25]
Chris, 

I am not sure "Pros/Cons" will work well in these screens. My current feeling is that we may have "Documents & Links", "Audio" and "Video".  In that way, all instructions and essential help is provided on the main screen and any extra resources are always available. Any views?

**Comment by chrismclarke** [comment]
I was just thinking that the naming didn't quite seem right. It's hard for me to be sure as I don't really know what the supporting materials would be like but how about a simpler/more-encompassing:
1. Introduction (where the text and question goes)
2. Resources (where we can put audio, text, documents etc)
3. Glossary (linked to terms found in the text)
?
