### ISSUE TITLE
Non-probability-based sampling

### ISSUE THREAD

**Issue by cebarahona** [stats4sd/Sampling-Decision-Assistant#32]
Is any sampling method based where some elements of the population have no chance of selection because the sampling strategy is based on decisions related to convenience, quotas or deliberate choice of elements of the population. In these cases, the probability of selection can't be determined. Because the selection of elements is non-random, non-probability-based sampling does not allow the estimation of sampling errors, and it is not possible to assume that biases cancel each other out. The ability of making inferences about the population is limited when using non-probability based sampling and the information generated needs to be treated carefully.
Some adaptations of non-probability-based sampling have been made to allow for limited inferences. An example of this is <Glossary/Respondent Driven Sampling, (RDS)/>, that proposes ways of estimating weights to try to account for biases in when using snowball sampling.

**Comment by chrismclarke** [comment]
I noticed that this glossary definition links to others. I've added the functionality to do so and implemented in 0.2.4. Will leave this open for quick review and close related glossary work.

**Comment by chrismclarke** [comment]
I've also temporarily changed the glossary page layout for our own use (highlighting what has been created and what is to be added)
