### ISSUE TITLE
Intro Sampling Decision Assistant

### ISSUE THREAD

**Issue by cebarahona** [stats4sd/Sampling-Decision-Assistant#34]
Chris, 

After my call this morning, I think we need to add a bit more context to the tool. What follows is an introduction to the tool. Right know I have the feeling that we will need to introduce a section that provides an introduction to non-probability-based sampling as well as the section on probability-based section  that includes the two buttons "step by step mode" and "Question-based mode". What follows is a short intro to the probability based section. In the text I have included the symbols "</" and "/>" to mark parts that should become links to the glossary or web links. I am not sure if this is possible, please advise.

Text of the introduction:

The purpose of the Sampling Decision Assistant is to provide a tool to support the design of sampling strategies among UNHCR staff when there is a need for primary data collection as mentioned in the <LINK/UNHCR Needs Assessment Handbook>. These operations often arise as part of needs assessment processes when not enough information is available from secondary sources. In those cases it is important to remember that the appropriateness and feasibility of different data collection methodologies will depend on:

•	The objectives of the primary data collection exercise
•	Constraints and limitations 
•	The context
•	The expected benefits and costs

A careful choice of the data collection methods is important, and whatever the choice, each has advantages and disadvantages. If sampling is involved in the process, then you will need to decide whether <Glossary/probability based sampling/> is possible, this will produce a sample that is representative of the population. Alternatively, the information may come from a sample drawn using <Glossary/non-probability based sampling/> which will have limitations in so far as making inferences about the population. Either choice has consequences on how the resulting information can be used. If you want to understand the difference between these two approaches see the resources section “Probability-based or non-probability-based sampling, that is the question!”.

The following screens will take you through a series of questions intended to help you thinking about decisions and information that is needed to design a sampling strategy that uses probability-based sampling. In other words, a sampling process that is intended to produce a <Glossary/representative sample/>

Other links:

UNHCR - Standardised Expanded Nutrition Survey (http://sens.unhcr.org/)
In particular the PRE-MODULE SURVEY STEPS AND SAMPLING that provides wider guidance on the process of implementing a sample survey.

UNHCR Needs Assessment Handbook (https://emergency.unhcr.org/entry/50209)

UN Handbook on Designing Household Survey Samples (https://unstats.un.org/unsd/demographic/sources/surveys/Handbook23June05.pdf)

**Comment by chrismclarke** [comment]
implemented 0.3.1, have included short tooltips to explain about glossary items, all text and relevant links.
