### ISSUE TITLE
Question 2.5 answered "No"

### ISSUE THREAD

**Issue by cebarahona** [stats4sd/Sampling-Decision-Assistant#35]
We may need to provide some help to guest-estimate the variance of the indicator. I would like to strongly encourage a numerical answer here. If the user does not have any idea, we should suggest:

1. find out from previous studies what is the variance of the estimate
2. Ask someone who may know
3. If everything fails, please take the difference between the minimum value and the maximum that came from 2.4, divided it by 5 and square the result. This will yield a very rough estimate of the variance that assumes that the distribution is roughly symmetric around the mean value.

**Comment by chrismclarke** [comment]
I've tried by changing 2.5 to yes/no and then having different questions render for 2.6 depending on response (either input as text or number the values if known, or input as number with calculation guidance if not known). 

We could change 2.4 to be a numerical min and max input and have the app automatically calculate if wanted, however I'm not sure if this would be necessary. Let me know what you think (live from v0.2.3)

**Comment by cebarahona** [comment]
Let me see how it works. I don't want an automated computation because everyone will go for it. Let's t me think about it


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by chrismclarke** [comment]
based on previous discussion assume implementation is fine, closing for now
