### ISSUE TITLE
What is this tool designed for?

### ISSUE THREAD

**Issue by cebarahona** [stats4sd/Sampling-Decision-Assistant#37]
I think we need a button before the two that take you to the questions to take the user to a general introduction about the tool. I have typed a page of text for the intro. Probably too much, and a good candidate for an audio clip or video. However, if we could initialy paste the text that would be great.

The text is in the document
"What is this tool designed for.docx" in the dropbox space at

UNHCR - Sampling\App design\text for the app screens

**Comment by chrismclarke** [comment]
have implemented a new screen and some extra content, as well as changing various aspects of design and user flow. Can explain in greater depth, or explore from v0.3.0 
https://unhcr-sampling-assistant.firebaseapp.com/

Still need to add the rest of the text and implement glossary link interaction (probably not linking to full glossary but  a small note to explain that is what will happen as you use the tool)
