### ISSUE TITLE
Build out core template

### ISSUE THREAD

**Issue by chrismclarke** [stats4sd/Sampling-Decision-Assistant#4]
Link start page to overview,
Populate overview page including links to 5 sections (use existing template from decisions/indicators)

**Comment by chrismclarke** [comment]
Turning my own attention to overview page now, plan to create a fairly rough mockup which can be improved on later to help with current workflow

**Comment by chrismclarke** [comment]
overview mockup done, just created other sections too

**Comment by chrismclarke** [comment]
@cebarahona I've added an extra 'overview' page which is the main hub for the step-by-step process. if you have a moment could you please quickly review, in particular noting whether the images I've selected for the different sections are relevant enough. 

Link at: unhcr-sampling-assistant.firebaseapp.com/#/overview

**Comment by dave-mills** [comment]
Looks like you have the basic overview page there. I'm going to bulk the current pages out somewhat on the page_organisation branch. Can merge in with what you're doing re: question management later.

**Comment by chrismclarke** [comment]
If I were you probably best to start with the general objectives page as this will be demo'd and im currently working on indicators page and some general structure

**Comment by dave-mills** [comment]
I've extended the 'home' page with the full menu of intended content. (Basically put it all on the page instead of hidden in the sidebar menu). 

I've also added some very rough and poorly formatted content to the Objectives page. I tried formatting it well, but I'm not at all efficient with these ion components.

**Comment by dave-mills** [comment]
Closing this for now and creating a bunch of related mini-issues...

**Comment by chrismclarke** [comment]
Just took a look through, tidied up a few bits and looks good. I like having the questions integrated through the document, will update the question component to make this easier to do. I think the general formatting for the text section is fine too, we don't need to get unecessarily fancy for short text documents.  For longer text then yes we will want to find ways to help guide the user through.
